format = """
[░▒▓](#ffc9d2)\
[  ](bg:#ffc9d2 fg:#090c0c)\
[](bg:#ffd2d9 fg:#ffc9d2)\
$directory\
[](fg:#ffd2d9 bg:#ffdbe1)\
$git_branch\
$git_status\
[](fg:#ffdbe1 bg:#ffe4e8)\
$nodejs\
[](fg:#ffe4e8 bg:#ffedf0)\
$time\
[ ](fg:#ffedf0)\
\n$character"""

right_format = """
$cmd_duration"""

[character]
success_symbol = '[❯](bold #ffc9d2) '
error_symbol = '[❯](bold red) '

[directory]
style = "fg:#090c0c bg:#ffd2d9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#ff85a1 bg:#ffdbe1)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#ff85a1 bg:#ffdbe1)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#ff85a1 bg:#ffe4e8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#ff85a1 bg:#ffedf0)]($style)'

[cmd_duration]
style = "#fff6f7"
format = '[󰚭 $duration ]($style)'
